### ISSUE TITLE
Add an option to share the crossword between browsers

### ISSUE THREAD

**Issue by zvibazak** [Dvd848/cryptic-crossword#2]
I checked it and it very simple. Attached some code for example.
The question is where to put the "share" button".

```
diff --git a/src/Display.ts b/src/Display.ts
index 1cd72fe..318fd3d 100644
--- a/src/Display.ts
+++ b/src/Display.ts
@@ -58,6 +58,7 @@ class StorageContext
     private readonly LOCAL_STORAGE_VCN_KEY = "VCN";
     private readonly LOCAL_STORAGE_VCN_VAL = "1";
     private readonly LOCAL_STORAGE_KEY_PREFIX = "crossword_";
+    private readonly LOCAL_STORAGE_URL_PARAM = this.LOCAL_STORAGE_KEY_PREFIX + "data";
 
     constructor(crossword_id: number, rows: number, cols: number)
     {
@@ -84,8 +85,15 @@ class StorageContext
 
     private loadInput()
     {
-        const input = localStorage.getItem(this.local_storage_key);
-
+        let input = localStorage.getItem(this.local_storage_key);
+       if (input == null || input == ""){
+            const urlParams = new URLSearchParams(window.location.search);
+            input = "";
+            if (urlParams.has(this.LOCAL_STORAGE_URL_PARAM)) {                
+               input = decodeURIComponent(urlParams.get(this.LOCAL_STORAGE_URL_PARAM));        
+            }
+        }
+        
         try
         {
             if (input == null || input == "")

```

**Comment by Dvd848** [comment]
Thanks! I think this is a good feature.
Using a URL parameter makes it very easy to share the solution between browsers (or friends), which is good. One drawback that I can think of though is that you might accidentally overwrite your own solution just by visiting a URL. 
One alternative is adding "export" and "import" buttons that allow the user to explicitly control the action, however they are a bit less friendly. What do you think? Would they be too annoying to use?

**Comment by zvibazak** [comment]
When we detect data from url - we can simply ask the user if he wants to get the data from url or not. That’s will save the UI clear and simple as it’s now. 

Do you need help implementing this feature or the other one?

**Comment by Dvd848** [comment]
Ok, sounds good.

> Do you need help implementing this feature or the other one?

Sure, pull requests are welcome (for any feature). I might be able to get to it myself after next week.
I'm thinking that the new URL parameter should be base64 encoded for a cleaner and shorter look.

> The question is where to put the "share" button".

We can try to start by putting it under the "check solution" button, it probably shouldn't be as wide though. It might require a few iterations until the UI seems reasonable. I think it might be best to have the button open a modal with a short explanation of the feature and a text field containing the URL + a "copy" button.

**Comment by zvibazak** [comment]
Well done. Thanks
