### ISSUE TITLE
לאפשר לסמן הגדרה כפתורה מהתצוגה הגדולה

### ISSUE THREAD

**Issue by zvibazak** [Dvd848/cryptic-crossword#3]
תודה על האתר.. אני נהנה כל שבוע. 
חשבתי על שיפור קטן - לאפשר לסמן הגדרה כפתורה מהתצוגה הגדולה
בתצוגה ניידת זה יותר רלוונטי כי צריך לסגור את המקלדת ואז לחפש את ההגדרה ולסמן.
דוגמא - לשים איפה שיש ריבוע אדום.
![image](https://github.com/Dvd848/cryptic-crossword/assets/17409580/1e10968d-0f0c-4892-9880-c0aafcc4f68c)
תודה רבה

**Comment by Dvd848** [comment]
זה רעיון טוב, תודה!
אנסה להוסיף, אבל זה עשוי לקחת קצת זמן.

(שמח לשמוע שהאתר מועיל!)

**Comment by Dvd848** [comment]
הוספתי בתור כפתור נפרד מעל ההגדרה הנוכחית.

**Comment by zvibazak** [comment]
תודה נראה מעולה!
